name: Pull Request Greeting

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Greet the user
      uses: actions/github-script@v6
      with:
        script: |
          const pr = context.payload.pull_request;
          const user = pr.user.login;
          const greetingMessage = `Hello @${user}, thank you for your pull request! 🎉`;
          const issueComment = {
            body: greetingMessage
          };
          await github.rest.issues.createComment({
            ...context.repo,
            issue_number: pr.number,
            ...issueComment
          });
