name: "Greet on PR Open"

on:
  pull_request:
    types: [opened]
    branches:
      - main # Only trigger when PR targets the 'main' branch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet contributor on PR open
        uses: actions/github-script@v6
        with:
          script: |
            const { context, github } = require('@actions/github');
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            await octokit.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Hi @${context.actor},\n\nThank you for contributing! 🎉 Your efforts are greatly appreciated. 🙌\n\n— _The Team_ 💙`
            });
