name: "Greet on PR Open"

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet contributor on PR open
        uses: actions/github-script@v6
        with:
          script: |
            const { context, github } = require('@actions/github');
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            await octokit.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🎉 **Welcome to the Project!** 🚀

              Hi @${context.actor},

              Thank you for opening this pull request! Your contribution is greatly appreciated. 🙌

              ### What Happens Next?
              - A maintainer will review your changes soon.
              - You might receive feedback or suggestions to improve your PR.
              - Once approved, your code will be merged into the project. 🎯

              If you have any questions or need assistance, feel free to ask here. We're here to help! 😊

              Thanks for being a part of our community and helping us grow. 🌟

              — _The Team_ 💙

              ![Welcome GIF](https://media.giphy.com/media/3o7abldj0b3rxrZUxW/giphy.gif)`
            });
