name: "Greet Contributor"

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        uses: actions/github-script@v6
        with:
          script: |
            const { context, github } = require('@actions/github');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🎉 Thank You for Contributing! 🙌\n\nHi there! 👋\n\nWe truly appreciate your time, effort, and contribution to this project. Your input helps make this project better.`,
            });
