name: "Greet Contributor"

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        uses: actions/github-script@v6
        with:
          script: |
            const github = require('@actions/github').getOctokit(process.env.GITHUB_TOKEN);
            await github.rest.issues.createComment({
              issue_number: github.context.issue.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: `## 🎉 Thank You for Contributing! 🙌\n\nHi there! 👋\n\nWe truly appreciate your time, effort, and contribution to this project. Your input helps make this project better for everyone! 🚀`
            });
